trigger:
  - main
  - fix/*

pool:
  vmImage: 'ubuntu-latest'
variables:
  imageName: 'genome-nexus'
  semanticVersion: '1.1.47'

steps:
  - task: Docker@2
    displayName: Build the genome-nexus image
    inputs:
      command: buildAndPush
      Dockerfile: Dockerfile
      repository: bioinformatics/cbioportal/$(imageName)
      containerRegistry: M2GENShared-ACR
      tags: $(semanticVersion).$(Build.BuildId)
